### ISSUE TITLE
Add unneccessary files and folders to .gitignore

### ISSUE THREAD

**Issue by rishacha** [noteblocks/noteblocks#11]
I think the following files and folders need to be kept under `.gitignore`

- [x] .keep
- [x] logs/
- [x] bin/
- [x] tmp/

**Comment by electron0zero** [comment]
.keep is to make sure we keep these folders, rails need these folders to be there.


bin should be checked in git, it has binstubs, see https://github.com/rbenv/rbenv/wiki/Understanding-binstubs
